registry:
  restart: always
  image: registry:2.7.1
  ports:
    - 443:443
  container_name: registry
  environment:
    REGISTRY_HTTP_ADDR: 0.0.0.0:443
    REGISTRY_HTTP_SECRET: testpassword
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/sandy.registry.com.crt
    REGISTRY_HTTP_TLS_KEY: /certs/sandy.registry.com.key
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    REGISTRY_STORAGE_DELETE_ENABLED: "true"

  volumes:
    - ./certs:/certs
    - ./auth:/auth
    - ./data:/data